AWSTemplateFormatVersion: 2010-09-09
Parameters:
  S3Bucketname:
    Type: String
    Default: enter-name-for-your-bucket
    Description: Enter a valid name for the bucket.
Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref S3Bucketname
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
            AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref MyS3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 
                - 's3:GetObject'
                - 's3:GetObjectVersion' 
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref MyS3Bucket
                - /*
          - Sid: ReadForCodeBuild
            Effect: Allow
            Principal: 'arn:aws:iam::643007106733:role/service-role/codebuild-react-music-player-service-role'
            Action: '*'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref MyS3Bucket
                - /*
Outputs:
  BucketURL:
    Value: !GetAtt MyS3Bucket.WebsiteURL
    Description: URL of the newly created S3 bucket
